services:
  # Service PostgreSQL
  postgres:
    image: postgres:15
    container_name: goofeat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: goofeat
      POSTGRES_PASSWORD: goofeat_password
      POSTGRES_DB: goofeat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goofeat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goofeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service MongoDB
  mongodb:
    image: mongo:6
    container_name: goofeat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: goofeat
      MONGO_INITDB_ROOT_PASSWORD: goofeat_password
      MONGO_INITDB_DATABASE: goofeat
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - goofeat-network
    command: ["--auth"]

  # Service MailHog pour tester les emails
  mailhog:
    image: mailhog/mailhog:latest
    container_name: goofeat-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Interface web
    networks:
      - goofeat-network

  adminer:
    image: adminer:latest
    container_name: goofeat-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    networks:
      - goofeat-network
    depends_on:
      - postgres

  # app:
  #   build: ./app
  #   container_name: goofeat-app
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - mailhog
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - goofeat-network

# Définition des volumes persistants
volumes:
  postgres_data:
  mongodb_data:

# Définition du réseau
networks:
  goofeat-network:
    driver: bridge
