apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goofeat

resources:
- ../../base

images:
- name: goofeat-back
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30080
  target:
    kind: Service
    name: goofeat-back

labels:
- pairs:
    environment: local
    deployment-method: self-hosted
  includeSelectors: false