apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/name: goofeat-back
    app.kubernetes.io/part-of: goofeat
  includeSelectors: false